title: Site

columns:
  - width: 1/2
    sections:
      news:
        headline: News
        type: pages
        sortBy: num desc
        parent: site.find("news")
        info: "{{ page.date.toDate('%d.%m.%Y') }}"
        limit: 20
  - width: 1/2
    sections:
      singlepages:
        type: pages
        headline: Sonstige Seiten
        sortBy: title
        template:
          - band
          - gigs
          - media-and-merch
          - press
          - imprint
          - privacy